### ISSUE TITLE
How to manually call the save method?

### ISSUE THREAD

**Issue by foxling** [SugarRecord/SugarRecord#101]
I found that when i call model.save() or model.endWriting(), they are not save to database.
Sometimes , I want to manually call the save method to save data immediately in database. 
like:
```
[MagicalRecord saveUsingCurrentThreadContextWithBlockAndWait:nil];
```

**Comment by foxling** [comment]
@pepibumur yes

**Comment by pepibumur** [comment]
Are you enabling the autosaving value of `DefaultCoreDataStack` @foxling ?

**Comment by foxling** [comment]
DefaultCDStack.startObserving() is only call in DefaultCDStack.backgroundContext(), but i'm not use backgroundContext, so the mergeChanges method is never called, the autosaving is not useful.

**Comment by pepibumur** [comment]
Why aren't you using the background context? The stack is setup to connect those context with the saving behaviour. @foxling

**Comment by deivuh** [comment]
I'm also the same problem. 

The autosaving value of `DefaultCoreDataStack` is enabled, but it won't write to the database after calling the `save()` method of a model. But if I send the app to the background (pressing the home button) it does write the data which I believe it's done by the `SugarRecord.applicationWillEnterForeground()` method.

**Comment by pepibumur** [comment]
Checked with the example project ant yes, there's a regression there @foxling and @deivuh , assigning a high priority to work on that as soon as possible. Thanks for the report guys

**Comment by pepibumur** [comment]
Solved @deivuh  and @foxling

**Comment by deivuh** [comment]
Thanks @pepibumur ! Really appreciate it

**Comment by foxling** [comment]
Thanks @pepibumur

**Comment by thewhitewood** [comment]
Had the same issue - pulled the latest off the repo and it's missing "SugarRecordArray" ?

**Comment by pepibumur** [comment]
@thewhitewood remove the group from XCode and add the entire library again because you're missing a new class I added to the library but that you haven't added to the XCode target as a file to be compiled.

**Comment by thewhitewood** [comment]
Cool - my bad :(
