### ISSUE TITLE
NSManagedObject.by() crashed.

### ISSUE THREAD

**Issue by iblacksun** [SugarRecord/SugarRecord#111]
If use NSManagedObject.by("xxx", equalTo:xxx), it's crashed in SugarRecordFinder line 267.

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse the format string "xxx == 5475f323e4b09e6d7a7a151e" '
 
I'm using version 1.0.5.

**Comment by pepibumur** [comment]
Show me the find line @iblacksun

**Comment by iblacksun** [comment]
@pepibumur 
>public func setPredicate<T: StringLiteralConvertible, R: StringLiteralConvertible>(byKey key: T, andValue value: R) -> SugarRecordFinder{
        self.predicate = NSPredicate(format: "\(key) == \(value)")
        return self
}


Line 267
> self.predicate = NSPredicate(format: "(key) == (value)")

**Comment by pepibumur** [comment]
can you try this ?
```swift
public func setPredicate(byKey key: T, andValue value: R) -> SugarRecordFinder{
  self.predicate = NSPredicate(format: "\(key) == '\(value)'")
  return self
}
```
**Notice the quotes around value**

**Comment by pepibumur** [comment]
@iblacksun

**Comment by iblacksun** [comment]
@pepibumur It's OK if add '' around value.

**Comment by pepibumur** [comment]
We'll change that soon https://github.com/SugarRecord/SugarRecord/issues/88 but in the meantime, that's a good solution!

**Comment by iblacksun** [comment]
@pepibumur OK, I,m using by(predicate:) now, it's ok.
