### ISSUE TITLE
File not found after pull

### ISSUE THREAD

**Issue by ransomweaver** [SugarRecord/SugarRecord#113]
I've pulled the latest SugarRecord Head (at 68140ad3689eb888f06921bc1e25cefa267ea0b3) and my project build now fails with this error:

<unknown>:0: error: no such file or directory: [pathremoved]/SugarRecord/library/Core/Protocols/SugarRecordObjectProtocol.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

I've cleaned and deleted everything in ~/library/Developer/Xcode/DerivedData/

Any idea how to get this running again?

**Comment by pepibumur** [comment]
@ransomweaver try to remove the library from your project and add it again following the steps, some files were removed and new ones added. This will be solved soon with the CocoaPods integration @ransomweaver .

**Comment by pepibumur** [comment]
@ransomweaver did you try it?
You can start using CocoaPods to integrate Swift libraries. SugarRecord is finally working with CocoaPods. Check out the Wiki section: https://github.com/SugarRecord/SugarRecord/wiki/Setup-SugarRecord

**Comment by ransomweaver** [comment]
@pepibumur Yes, it worked. I'm going to try Cocoapods now.
