### ISSUE TITLE
Filename used twice error when using Cocoapods

### ISSUE THREAD

**Issue by deivuh** [SugarRecord/SugarRecord#115]
Hi, 
When I setup SugarRecord with Cocoapods, I get the following error for each of the SugarRecord files:
```
<unknown>:0: error: filename "CDArray+SugarRecordResults.swift" used twice: 
'/Users/user/Projects/project/Pods/SugarRecord/library/CoreData/Base/CDArray+SugarRecordResults.swift' and '/Users/user/Projects/project/Pods/SugarRecord/library/CoreData/Base/CDArray+SugarRecordResults.swift'
```

For the setup, I had to specify the git source on the Podfile, but everything installed fine.

Did I miss something?

**Comment by pepibumur** [comment]
Did you try the pre-release version @deivuh ?

**Comment by deivuh** [comment]
I had the 0.36.0 prerelease version installed, but apparently the binary was still from 0.35.0. 

Had to uninstall Cocoapods and delete the binary manually to get the 0.36.0 binary installed. 

Now with 0.36.0 and the updated wiki instructions, it's working fine. Thanks @pepibumur, I wouldn't notice if you didn't ask.
