### ISSUE TITLE
missing header RestKit.h

### ISSUE THREAD

**Issue by gaming-hacker** [SugarRecord/SugarRecord#117]
cloned repo, it's no where to be found but bridging header is looking for it.

**Comment by pepibumur** [comment]
How did you integrate it @gaming-hacker ?

**Comment by gaming-hacker** [comment]
cloned it.
tried to compile the example by default
i search the cloned repo and there's no Restkit.h

**Comment by pepibumur** [comment]
Have you tried to get the git submodules @gaming-hacker ?

**Comment by gaming-hacker** [comment]
d'oh, let me look.

**Comment by gaming-hacker** [comment]
yes forgot to include.
