### ISSUE TITLE
CoreData+iCloud with Sugar Record

### ISSUE THREAD

**Issue by JamalK** [SugarRecord/SugarRecord#129]
Hi,
I'm trying to build an app that uses CoreData+iCloud but when I'm trying to add the stack I'm getting a crash, can you please tell me what am I doing wrong here?  I'm calling the following lines after didFinishLaunchingWithOptions. 

```
let data: iCloudData = iCloudData(iCloudAppID: "iCloud.com.jamalDesigns.ShapNote", iCloudDataDirectoryName: "data.nosync", iCloudLogsDirectory: "")
        
        let icloudStack = iCloudCDStack(databaseName: "Database.sqlite", icloudData: data)
        
        SugarRecord.addStack(icloudStack)
```

and I'm getting the following crash message 

```
SR-Info: Stack -SugarRecord.iCloudCDStack- added to SugarRecord 
SR-Info: Initializing the stack: Stack to connect your local storage with iCloud 
2015-02-18 15:36:03.402 ShapNote[61170:7218400] *** NSForwarding: warning: object 0x7ffe21440200 of class 'SugarRecord.iCloudCDStack' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[SugarRecord.iCloudCDStack storeDidChange:]
```

Thank you.

**Comment by dchavezlive** [comment]
We are currently looking into it. We should have a fix later today! :)

**Comment by pepibumur** [comment]
I'm with it! thanks for the report @JamalK

**Comment by pepibumur** [comment]
@JamalK the initialization process is asynchronous so you've to make sure there're no operations executed when it's being initialized. Check this pull request https://github.com/SugarRecord/SugarRecord/issues/128 where @dchavezlive applied it to the example project which also failed.
Keep us updated with the status of this and thanks for the report

**Comment by JamalK** [comment]
@pepibumur I actually made sure it's being initialized, and no other operations are taking place. It's still crashing the same way. Thanks.

**Comment by dchavezlive** [comment]
If you share your project with me, I wouldn't mind taking a look. Otherwise, have you tried the new solution anyway, with listening for the notification? If so, does it still show the same error?

**Comment by JamalK** [comment]
Sorry for the late reply!
I just tried using the latest version of Sugar Record, and it seems to be fixed the previous crash. 
Thank you!
