### ISSUE TITLE
Error "Extra argument 'equalTo' in call" occurs when using more than one ".by" operation

### ISSUE THREAD

**Issue by tyleramos** [SugarRecord/SugarRecord#133]
I'm receiving the following error when trying to filter my result set by multiple criteria:
"Extra argument 'equalTo' in call"

Here's my example:
```
var scope = ContactCard.by("contactId", equalTo: self.id).by("ownerId", equalTo: self.id)
scope.first().find().firstObject() as ContactCard
```

In the documentation, it briefly mentions that concatenation can be used:

> Filtering and sortering methods can be concatenated and finally fetched using find()

There are no examples though so I might be reading into this statement a bit.  Is it possible to filter of multiple attributes?

**Comment by dchavezlive** [comment]
The fault was in a commit made some time ago that has now been reverted. It should work as expected now.
