### ISSUE TITLE
`Extra argument 'equalTo' in call`

### ISSUE THREAD

**Issue by robertjwhitney** [SugarRecord/SugarRecord#134]
This issue is similar to #133, but I get the error with only one `.by`

`Klass.by("attribute", equalTo: "value")`

Returns: `Extra argument 'equalTo' in call`

Figured it had to be a recent commit, and found that rolling back https://github.com/SugarRecord/SugarRecord/commit/a04095dc7ef11322d80d05cef9090d2dad77c5c3 fixes it, so I'm assuming this is also an area where test coverage could be improved.

**Comment by avielg** [comment]
As a temp workaround i added:
    extension String: Printable {
        public var description: String { return self }
    }

**Comment by dchavezlive** [comment]
https://github.com/SugarRecord/SugarRecord/commit/a04095dc7ef11322d80d05cef9090d2dad77c5c3 as been reverted. Things should work as expected.

**Comment by robertjwhitney** [comment]
Why was it merged in the first place, and how can these sorts of bugs be prevented in the future?
