### ISSUE TITLE
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by brandy2015** [SugarRecord/SugarRecord#140]
I don't know why it happened.I try a lot of time to figure it out ,but failed. Could you give me some advice to slove it?
![2015-03-28 18 00 49](https://cloud.githubusercontent.com/assets/10484324/6880587/985ce22a-d574-11e4-8e52-2ba3c8c3ad25.png)

**Comment by dchavezlive** [comment]
You can solve this by opening terminal and navigating to the example directory in the download. You may do this by typing: ```cd [path to downloaded file]/example``` and pressing Enter. Then in the terminal type: ```pod install``` and press Enter then wait for it to complete.

NOTE: For the first step you can also open a terminal type: ```cd ``` then drag the example folder from Finder into the terminal to populate the path and press Enter.
