### ISSUE TITLE
Wiki and Example project don't match

### ISSUE THREAD

**Issue by Brisdo** [SugarRecord/SugarRecord#142]
This is confusing.  The Wiki says "Transactions - Operations like edition/deletion/creation MUST be grouped in a transaction.  The way to group different operations into a single trasaction is using the following methods..." 
```
context.beginWriting()
context.endWriting()
```

But creation in the example uses just save().  When you click to button to create a new record, it calls the the "add" function which :
```swift
let model = CoreDataModel.create() as CoreDataModel
model.text = formatter.stringFromDate(NSDate())
model.save()
```

**Comment by dchavezlive** [comment]
Indeed there was an error in the Wiki. save() internally invokes the ```beginWriting() && endWriting()``` and as such it is not necessary to use them when creating and saving an object.
