### ISSUE TITLE
NSPredicate - Unable to generate SQL for predicate

### ISSUE THREAD

**Issue by avielg** [SugarRecord/SugarRecord#144]
There is a problem with `setPredicate` method in `SugarRecordFinder` where missing quotes symbols causes the app to crash when filtering an entity with `by` method.
The simple solution is to switch this line (SugarRecordFinder.swift:267)  

    self.predicate = NSPredicate(format: "\(key) == \(value)")

With this:

    self.predicate = NSPredicate(format: "\(key) == '\(value)'")

This problem is mentioned (and solved the same way) here: http://stackoverflow.com/a/7662353/2242359

**Comment by dchavezlive** [comment]
Pull request has been merged!
