### ISSUE TITLE
Why doesn't this SugarRecord.operation save?

### ISSUE THREAD

**Issue by jimijon** [SugarRecord/SugarRecord#83]
I am doing a sync of my database.
func syncCategories(){
        
        var fullStringURL = self.baseStringURL + "/Category.json"
        let URL = NSURL(string:fullStringURL)!
        defaults.objectForKey("lastCategoryUpdate")
        let dateString = defaults.objectForKey("lastCategoryUpdate")! as String
        let parameters:[String:AnyObject] = ["lastmoddate":dateString]

        
        Alamofire.request(.GET, URL, parameters: parameters)
            .responseJSON { (req, res, json, error) in
                if(error != nil) {
                    NSLog("Error: \(error)")
                    println(req)
                    println(res)
                }
                else {
                    var json = JSON(json!)
                    
                    SugarRecord.operation(inBackground: true, stackType: SugarRecordStackType.SugarRecordStackTypeCoreData, closure: { (context) -> () in
                        context.beginWriting()
                    
                        for (index: String, subJson: JSON) in json {
                            if let extId:NSNumber = subJson["id"].number{
                                
                                var category: Categorization? = Categorization.by("extID", equalTo: "\(extId)").find()?.first as Categorization?
                                
                                if(category == nil){
                                    category = Categorization.create(inContext: context) as? Categorization
                                    context.insertObject(category!)
                                }
                                
                                category!.extID = extId
                                
                                if let userName = subJson["name"].string{
                                    category!.name = userName
                                }
                                if let mainImage = subJson["mainImage"].string{
                                    category!.mainImageURL = mainImage
                                }
                                if let thumbnailImage = subJson["thumbnailImage"].string{
                                    category!.thumbnailURL = thumbnailImage
                                }

                                
                            }else{
                                //skip
                            }
                        }
                        context.endWriting()
                    })
                }
        }
        
    }

**Comment by pepibumur** [comment]
It should be fixed here @jimijon https://github.com/SugarRecord/SugarRecord/pull/104
